### ISSUE TITLE
Dimensions API dependencies

### ISSUE THREAD

**Issue by ceteri** [NYU-CI/RCApi#3]
Where does the `dimensions_search_api_client.py` file come from?

It looks like a downloaded API client. Is there a related `pip` install for it?

We'll need to resolve that to make this library something that we can integrate into several other projects as a subpackage.

Thanks!

**Comment by srand525** [comment]
see https://github.com/NYU-CI/RCApi/pull/6
dependency is removed from rcapi and we can remove `dimensions_search_api_client .py` from repo.
