### ISSUE TITLE
Dimensions dataset lookup

### ISSUE THREAD

**Issue by ceteri** [NYU-CI/RCApi#5]
Were there any examples of using the Dimensions API to lookup dataset/publication links?

**Comment by srand525** [comment]
I've been doing this work from RCCustomers. I put an example of how I've been doing it [here](https://github.com/NYU-CI/RCCustomers/tree/master/customers/pull_linkages_example)

 and created a diagram [here](https://docs.google.com/presentation/d/11hgToKwvM2hOIY99KPSS81YEUECHgFnL65fQkgvTY3Y/edit?folder=0AIhjBbULCGLlUk9PVA#slide=id.g6b9b1e778e_0_36)

**Comment by ceteri** [comment]
Wrong answer.
